name: Test

on:
  push:
    branches:
      - '*'
    tags:
      - '!*'

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: ['3.0.5', '2.7.7']
        rails-version: ['6.1', '6.0']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsqlite3-dev
    - name: Build and test with Rspec
      run: |
        gem install bundler:1.17.3
        bundle install --jobs 4 --retry 3
        bundle exec rspec
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.rails-version }}.gemfile
